server:
  port: 8090            # 端口号
spring:
  datasource:
    username: root      # 数据库名
    password: 123456      # 数据库密码
    url: jdbc:mysql:///role_6

  data:
    redis:
      port: 6379
      host: localhost
logging:
  level:
    com.example.web_role: debug
mybatis-plus:
  mapper-locations:
    classpath:mapper\*.xml